### ISSUE TITLE
Changing the "full text pdf" button

### ISSUE THREAD

**Issue by drever** [quantum-journal/o3po#118]
The "full text pdf" button in the abstract is implemented by the plugin as a `form`. The theme of compositionality uses `a href` to implement a button. This makes styling the "full text pdf" button difficult. 

Should we move this to the settings? This would mean, that HTML-Code is in the settings.

**Comment by cgogolin** [comment]
I am actually not happy with the curren <form> based solution.

Could you submit a PR that changes the full text button of the primary publication type and the print button of the secondary one to a <a href="">?

**Comment by cgogolin** [comment]
closed per #144
